### ISSUE TITLE
Add needed dependencies to "Installation" section

### ISSUE THREAD

**Issue by biolypl** [faustbrian/Ark-PHP-Client#13]
Kindly please add needed dependencies to install section, "composer require" simple command doesn't work

**Comment by faustbrian** [comment]
What error message do you get?

**Comment by biolypl** [comment]
I had to install: php7.1, php7.1-mbstring
Adding these two packages to install instruction would solve my problems

**Comment by faustbrian** [comment]
I won't be adding these to the install instructions because this is a PHP Package and looking at the `composer.json` should tell every modern developer that works with composer that PHP 7.1 is required and `php71-mbstring` is something that should always be installed.
