### ISSUE TITLE
PHP notice + PHP warning when create transaction

### ISSUE THREAD

**Issue by biolypl** [faustbrian/Ark-PHP-Client#16]
I try to create new transaction in ARK devnet. `$client` is configured good, other api queries works but with transaction code ($pass is my passhprase as string):
```
try {
    $response = $client->api('Transaction')->create('D59NTfV92ca9QevUydvMiFMFdubbCaAVCV', 1250, 'test', $pass, $secondSecret = null);
    dd('Everything OK!', $response);
} catch(BrianFaust\Ark\Exceptions\InvalidResponseException $e) {
    dd($e->getMessage());
}
```
Catch this error:
```
PHP Notice:  Trying to get property of non-object in /.../vendor/faustbrian/ark-php-client/src/API/Transaction.php on line 89
PHP Warning:  Creating default object from empty value in /.../vendor/faustbrian/ark-php-client/src/API/Transaction.php on line 89
string(34) "Unknown transaction type undefined"
```

**Comment by faustbrian** [comment]
Do you have arkjs and nucleid properly installed and set the path?

⁣Sent from TypeApp ​

**Comment by biolypl** [comment]
Installed globally, by what you mean with set the path?

**Comment by faustbrian** [comment]
While creating an instance of the client there is an optional parameter for the path where nucleid can be found https://github.com/faustbrian/Ark-PHP-Client/blob/master/src/Client.php#L45-L52

If you want to see what nucleid generates you can go to this line https://github.com/faustbrian/Ark-PHP-Client/blob/master/src/API/Transaction.php#L86 and place `dd($transaction);` after it and execute your script. You will see the response from nucleid as an object.

**Comment by faustbrian** [comment]
This snippet for example works without any issues. See how I set the path at the end of the constructor so Nucleid can execute `/usr/local/bin/nucleid`. On most servers the default path for it should be `/usr/bin` though.

```php
<?php

require_once 'vendor/autoload.php';

$client = new BrianFaust\Ark\Client(
    'ark-node-ip',
    4001,
    '6e84d08bd299ed97c212c886c98a57e36545c8f5d645ca7eeae63a8bd62d8988',
    '1.0.1',
    '/usr/local/bin'
);

try {
    $response = $client->api('Transaction')->create(
        'recipient-ark-addres',
        1 * 10 ** 8,
        'env-testing-vendor',
        'secret',
        'second-secret'
    );

    dd($response);
} catch (BrianFaust\Ark\Exceptions\InvalidResponseException $e) {
    dd($e->getMessage());
}
```

**Comment by biolypl** [comment]
I set the path to "/usr/local/bin" but it doesn't help. `dd($transaction)` return NULL and I guess here is problem

**Comment by faustbrian** [comment]
Then your nucleid is not installed there. Run `which nucleid` or `whereis nucleid` and figure out where it is installed.

**Comment by biolypl** [comment]
It is:
```
ubuntu@ubuntu-xenial:~$ whereis nucleid
nucleid: /usr/local/bin/nucleid
```

**Comment by faustbrian** [comment]
Then your user either has no permission to execute nucleid or somehow you managed to put in wrong data.

You can also go to https://github.com/faustbrian/Ark-PHP-Client/blob/master/src/Utils/Nucleid.php#L91 and place `dd("nucleid -r {$this->require} -e {$this->execute} {$this->buildArguments()} --ojson 2>&1 &");` after copy&paste the result to your terminal and execute it manually to see any malformed data by chance.

**Comment by biolypl** [comment]
Above dd function return well looking command, but after excution from terminal in this form:
`nucleid -r arkjs -e transaction.createTransaction "D59NTfV92ca9QevUydvMiFMFdubbCaAVCV" 100000000 "test" "pass"  --ojson > test.log 2>&1`
`test.log` is empty

**Comment by faustbrian** [comment]
Only execute `nucleid -r arkjs -e transaction.createTransaction "D59NTfV92ca9QevUydvMiFMFdubbCaAVCV" 100000000 "test" "pass" --ojson` but looks like something on your system is wrong.

**Comment by biolypl** [comment]
New vagrant Ubuntu 16 instance, everything installed and now this error:
```
PHP Fatal error:  Uncaught TypeError: json_decode() expects parameter 1 to be string, null given in /home/ubuntu/ark-php/vendor/faustbrian/ark-php-client/src/Utils/Nucleid.php:93
Stack trace:
#0 /home/ubuntu/ark-php/vendor/faustbrian/ark-php-client/src/Utils/Nucleid.php(93): json_decode(NULL)
#1 /home/ubuntu/ark-php/vendor/faustbrian/ark-php-client/src/API/Transaction.php(86): BrianFaust\Ark\Utils\Nucleid->send()
#2 /home/ubuntu/ark-php/test.php(25): BrianFaust\Ark\API\Transaction->create('D59NTfV92ca9Qev...', 100000000, 'test', 'pass...', NULL)
#3 {main}
  thrown in /home/ubuntu/ark-php/vendor/faustbrian/ark-php-client/src/Utils/Nucleid.php on line 93
```
The `$output` is NULL, so for me looks like Nucleid command is real problem
`nucleid -r arkjs -e transaction.createTransaction "D59NTfV92ca9QevUydvMiFMFdubbCaAVCV" 100000000 "test" "pass" --ojson`
as before, return nothing while executing from terminal. Other methods work so I really can't debug that one

**Comment by faustbrian** [comment]
I have this package running in production without any issues whatsoever so the nucleid command is not the "real problem".

I tested the example I posted in a Vagrant instance with Ubuntu 16 and it works flawlessly, he issue is on your end which is either caused by permissions or invalid settings.
