### ISSUE TITLE
don't use unsecure API leaking passphrase

### ISSUE THREAD

**Issue by fix** [faustbrian/Ark-PHP-Client#3]
here:
https://github.com/faustbrian/Ark-PHP-Client/blob/master/src/API/Transaction.php#L80
https://github.com/faustbrian/Ark-PHP-Client/blob/master/src/API/Delegate.php#L96

and all other ->create functions

Instead you should use local algorithm to generate keys and sign the transaction ON THE CLIENT.
See algo examples for instance here: https://github.com/ArkEcosystem/ark-java/blob/master/src/main/groovy/io/ark/core/Transaction.groovy

I would suggest to use the ark-js lib on the client and then send back the signed tx on PHP before being handled (stored and/or broadcasted)

**Comment by faustbrian** [comment]
The issue with using ark-js is that I am running a cronjob for PHP that automatically processes payments. The passphrase are encrypted on the server side of things.

I will take a look at the algorithm and might add a note to the README about avoiding to use these methods.

**Comment by fix** [comment]
ah ok.
Anyway passphrase is sent in clear on the network. So what i would suggest then is to use develop a simple REST client running locally handling all this things as a daemon and then handle connection to it via PHP. That way you proxy locally the creation of the transaction and don't send passphrase away on the network.

**Comment by faustbrian** [comment]
Do you have an example of what you mean by the REST client that works as a proxy?

**Comment by fix** [comment]
not yet developed, but was thinking a simple nodejs express server reusing ark-js functions

**Comment by faustbrian** [comment]
So you would have an express server running that would have the secret & second secret hardcoded and just accepts for example a POST request with an ark address and amount and it would create the transaction directly via ark.js instead of sending an HTTP request?

**Comment by fix** [comment]
something as simple as
```
var express = require('express');
var app = express();

app.put('/transaction/create', function (req, res) {
  res.send(arkjs.transactions.createTransaction(req.address, req.address, req.amount, req.vendorField, req.passphrase));
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

**Comment by faustbrian** [comment]
So I would build something simple as that and then send all my requests to http://localhost:3000/transactions/create <http://localhost:3000/transactions/create> instead of directly to http://ark-node.my.network:4001/api/transactions/create <http://ark-node.my.network:4001/api/transactions/create> right?

**Comment by faustbrian** [comment]
@fix Switched my application now to this express server for processing the transactions.

```js
// Load config...
require('dotenv').config();

// Arrange...
var express = require('express'),
    bodyParser = require('body-parser'),
    request = require('request'),
    ark = require('arkjs'),
    app = express();

// Route...
app.post('/transaction/create', bodyParser.json(), function(req, res) {
    var transaction = ark.transaction.createTransaction(
        req.body.address,
        parseInt(req.body.amount),
        process.env.VENDOR,
        process.env.SECRET,
        process.env.SECOND_SECRET
    );

    request({
        url: 'http://ip:port/peer/transactions',
        json: {
            transactions: [transaction]
        },
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'version': '0.1.0',
            'port': 1,
            'nethash': 'nethash'
        }
    }, function(error, response, body) {
        res.send(error || body);
    });
});

// Listen...
app.listen(3000, function() {
    console.log('Example app listening on port 3000!');
});
```

**Comment by faustbrian** [comment]
I have added a note to the README file that it is advised to use an ExpressJS like setup to function as a Proxy for more security. When I have some free-time I will take a look at the algorithms and see if it is worth implementing them.

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Ark-PHP-Client/commit/1a8773b6a87537066d191d09e9a460957878c7e8

**Comment by vmunich** [comment]
Is it still advisable to run a service locally for sending transactions, and query that service from PHP instead of directly querying my node? 

Also it seems that /api/transactions has been deprecated and replaced with /peer/transactions.

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Ark-PHP-Client/blob/master/docs/Installation.md
https://github.com/faustbrian/Ark-PHP-Client/blob/master/src/API/Transaction.php#L68-L104

**Comment by vmunich** [comment]
Transaction->create is only working on the mainnet:
```$tx = Lark::api('Transaction')->create('DKfEF2sykKCZzom3vFg1dp9D2kisB8hM2Q', 10, 'testing', 'word word word word word word word word word word word word', null);

UnexpectedValueException with message '(node:29824) UnhandledPromiseRejectionWarning: Unh                            andled promise rejection (rejection id: 1): Error: Wrong recipientId'```

Darknet addresses are failing validation on arkjs https://github.com/ArkEcosystem/ark-js/blob/4f7ef0075c3d5694126ec530281e06b365bfb699/lib/transactions/transaction.js#L9

Works fine when using the mainnet. https://github.com/ArkEcosystem/ark-js/blob/95b591c4641ab12869890889c9e3cbbcbe457166/lib/transactions/crypto.js#L392 Looks like it fails to send through the devnet's nethash so arkjs uses the default mainnet nethash? I'm unable to verify.

**Comment by faustbrian** [comment]
Feel free to send a PR for devnet support, pretty easy to do if you know how to switch the network with ark-js.
